### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zoelir729** [vsoch/TtoZ#4]
TtoZ --t_stat_map=$t_stat_nii --dof=$dof --output_nii=$output_nii
error occured, is there a fix way?

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/TtoZ", line 33, in <module>
    sys.exit(load_entry_point('TtoZ==0.1.2', 'console_scripts', 'TtoZ')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/TtoZ", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/TtoZ/scripts.py", line 31
    print "Converting map %s to Z-Scores..." %(args.t_stat_map)
          ^
SyntaxError: invalid syntax

**Comment by vsoch** [comment]
Absolutely! Could you please test the branch with the fix here? https://github.com/vsoch/TtoZ/pull/5
